openapi: 3.0.3
info:
  title: VK Internship API
  version: 1.0.0
  description: API for user authentication and listings management.
servers:
  - url: http://localhost:8080
  - url: http://papaya-copper13073.my-vm.work
paths:
  /auth/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: Successfully registered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterResponse'
        '422':
          description: Invalid input
  /auth/login:
    post:
      summary: Login an existing user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Successfully authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '401':
          description: Unauthorized
        '422':
          description: Invalid input
  /listings:
    get:
      summary: Get a list of listings
      parameters:
        - in: query
          name: sort_by
          schema:
            type: string
            enum: [created_at, price]
          description: Sort by field
        - in: query
          name: sort_order
          schema:
            type: string
            enum: [asc, desc]
          description: Sort order
        - in: query
          name: limit
          schema:
            type: integer
            default: 10
        - in: query
          name: offset
          schema:
            type: integer
            default: 0
        - in: query
          name: price_min
          schema:
            type: number
        - in: query
          name: price_max
          schema:
            type: number
      responses:
        '200':
          description: A list of listings
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ListingWithAuthor'
        '401':
          description: Token is provided, but is invalid
        '500':
          description: Internal Server Error
    post:
      summary: Create a new listing
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateListingRequest'
      responses:
        '201':
          description: Successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListingWithAuthor'
        '400':
          description: Invalid input
        '401':
          description: Unauthorized
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    LoginRequest:
      type: object
      required: [username, password]
      properties:
        username:
          type: string
        password:
          type: string
    LoginResponse:
      type: object
      properties:
        token:
          type: string
    RegisterRequest:
      type: object
      required: [username, password]
      properties:
        username:
          type: string
          minLength: 3
          maxLength: 32
        password:
          type: string
          minLength: 6
          maxLength: 128
    RegisterResponse:
      type: object
      properties:
        user:
          $ref: '#/components/schemas/User'
        token:
          type: string
    CreateListingRequest:
      type: object
      required: [title, description, image_url, price]
      properties:
        title:
          type: string
          minLength: 3
          maxLength: 100
        description:
          type: string
          minLength: 10
          maxLength: 500
        image_url:
          type: string
          format: uri
        price:
          type: number
          minimum: 0.01
    ListingWithAuthor:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        image_url:
          type: string
          format: uri
        price:
          type: number
        author_login:
          type: string
        is_owned:
          type: boolean
        created_at:
          type: string
          format: date-time
    User:
      type: object
      properties:
        id:
          type: integer
        username:
          type: string
        created_at:
          type: string
          format: date-time
